MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Models/AnimalNotDonkey.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NotDonkeyApp_UG.Models
{
    public class AnimalNotDonkey
    {
        public int Id { get; set; }

        [Required]
        public int OwnerPhoneNumber { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Name length can't be more than 30.")]
        public string Name { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Password length can't be more than 30.")]
        public string Password { get; set; }

        [Required]
        public string AnimalType { get; set; } // also name of avatar

        [Required]
        [StringLength(15)]
        public string Sex { get; set; }

        [Required]
        [Range(0, 2137, ErrorMessage = "Oops")]
        public int Weight { get; set; }

        [Required]
        [StringLength(2137, ErrorMessage = "Additional Description may contain up to 2137 letters")]
        public string AdditionalDescription { get; set; }

        [Required]
        public bool IsDonkey { get; set; }

        public string AnimalsYouLike { get; set; }
    }
}

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Models/AnimalWikiInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NotDonkeyApp_UG.Models
{
    public class AnimalWikiInformation
    {
        public int Id { get; set; }
        public string AnimalName { get; set; }
        public string Information { get; set; }
    }
}

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Models/ErrorViewModel.cs
using System;

namespace NotDonkeyApp_UG.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Controllers/AnimalNotDonkeysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GraniteHouse.Data;
using NotDonkeyApp_UG.Models;
using NotDonkeyApp_UG.Services;
using NotDonkeyApp_UG.Data;

namespace NotDonkeyApp_UG.Controllers
{
    public class AnimalNotDonkeysController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AnimalNotDonkeysController(ApplicationDbContext db)
        {
            _db = db;
        }

        #region Controller Basic Methods
        public IActionResult Index()
        {
            try
            {
                var listOfAllUsers = _db.NotDonkeys.ToList();

                return View(listOfAllUsers);
            }
            catch (Exception ex)
            {
                SetErrorDetails(ex, "An error occured during trying to reach main page");
                return RedirectToAction("ThrowErrorMessage");
            }
        }

        public IActionResult AllAnimals()
        {
            try
            {
                if (!StaticDetails.DonkeysAvailableToLike.Any())
                {
                    var listOfAllUsers = _db.NotDonkeys.ToList();

                    StaticDetails.DonkeysAvailableToLike = listOfAllUsers;

                    return View(listOfAllUsers);
                }
                else
                {
                    return View(StaticDetails.DonkeysAvailableToLike);
                }
            }
            catch (Exception ex)
            {
                SetErrorDetails(ex, "An error occured during trying to display all animals");
                return RedirectToAction("ThrowErrorMessage");
            }
        }

        public IActionResult AddAnimalToFavourites(int id)
        {
            try
            {
                var user = _db.NotDonkeys.Find(StaticDetails.CurrentUserId);
                if (user != null)
                {
                    user.AnimalsYouLike += $"{id.ToString()}.";
                    StaticDetails.DonkeysAvailableToLike.Remove(StaticDetails.DonkeysAvailableToLike.Where(x => x.Id == id).SingleOrDefault());
                    _db.SaveChanges();
                    StaticDetails.DonkeysAvailableToLike = _db.NotDonkeys.ToList();
                }
                return RedirectToAction("AllAnimals");
            }
            catch (Exception ex)
            {
                SetErrorDetails(ex, "An error occured during trying to Add animal to your favourites");
                return RedirectToAction("ThrowErrorMessage");
            }
        }

        public IActionResult PairedAnimals()
        {
            try
            {
                var user = _db.NotDonkeys.Find(StaticDetails.CurrentUserId);
                if (user != null)
                {
                    var allAnimalLikedids = AnimalService.Instance.ProceedUserIds(user.AnimalsYouLike ?? String.Empty);
                    List<AnimalNotDonkey> yourAnimalsList = new List<AnimalNotDonkey>();

                    foreach (var id in allAnimalLikedids)
                    {
                        yourAnimalsList.Add(_db.NotDonkeys.Find(id));
                    }

                    return View(yourAnimalsList);
                }

                return View(new List<AnimalNotDonkey>());
            }
            catch (Exception ex)
            {
                SetErrorDetails(ex, "An error occured during trying to get all paired animals");
                return RedirectToAction("ThrowErrorMessage");
            }
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(int ownerPhoneNumber, string password)
        {
            try
            {
                var user = _db.NotDonkeys.FirstOrDefault(x => x.OwnerPhoneNumber == ownerPhoneNumber);

                if (user != null)
                {
                    if (user.Password == password)
                    {
                        StaticDetails.CurrentUserId = user.Id;

                        return RedirectToAction("PairedAnimals");
                    }
                }
                StaticDetails.IsUserLogged = true;
                return View();
            }
            catch (Exception ex)
            {
                SetErrorDetails(ex, "An error occured during Logging in");
                return RedirectToAction("ThrowErrorMessage");
            }
        }

        public IActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                SetErrorDetails(ex, "An error occured");
                return RedirectToAction("ThrowErrorMessage");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OwnerPhoneNumber,Name,Password,AnimalType,Sex,Weight,AdditionalDescription,IsDonkey,AnimalsYouLike")] AnimalNotDonkey animalNotDonkey)
        {
            try
            {
                if (ModelState.IsValid && !animalNotDonkey.IsDonkey)
                {
                    animalNotDonkey.AnimalType = AnimalService.Instance.SetAnimalType(animalNotDonkey.AnimalType);
                    _db.Add(animalNotDonkey);
                    await _db.SaveChangesAsync();
                    StaticDetails.DonkeysAvailableToLike = _db.NotDonkeys.ToList();
                    return View("Login");
                }
                return View(animalNotDonkey);
            }
            catch (Exception ex)
            {
                SetErrorDetails(ex, "Error occured during creating new animal");
                return RedirectToAction("ThrowErrorMessage");
            }
        }

        public IActionResult ThrowErrorMessage()
        {
            return View();
        }

        public IActionResult UserProfile()
        {
            if (StaticDetails.CurrentUserId > 0)
            {
                var currentUser = _db.NotDonkeys.Find(StaticDetails.CurrentUserId);
                return View(currentUser);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        #endregion

        #region Helper Methods
        private void SetErrorDetails(Exception ex, string msgToDisplay)
        {
            StaticDetails.CurrentErrorMsg = $"An error occured due to : {ex.Message}";
            StaticDetails.AdditionalErrorInfo = msgToDisplay;
        }
        #endregion
    }
}

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Views/AnimalNotDonkeys/AddNewAnimal.cshtml
@{
    ViewData["Title"] = "AddNewAnimal";
}

<body style="background-color:lightblue">
    <h2>Add new information about animal</h2>
    <br />
    <div ng-controller="ExampleController">
        <form novalidate class="simple-form">
            <label>Name: <input type="text" ng-model="animal.name" /></label><br />
            <label>Information: <input type="text" ng-model="animal.info" /></label><br />
            <input type="submit" ng-click="add(animal)" value="Add" />
        </form>
    </div>

    <script>

    </script>
</body>

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Views/AnimalNotDonkeys/AllAnimals.cshtml
@model IEnumerable<AnimalNotDonkey>
@using NotDonkeyApp_UG.Data;
@{
    ViewData["Title"] = "AllAnimals";
}
<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>


<body style="background-color:lightblue">
    <h1>Check out our all verified Animals ヽ(◕ヮ◕ヽ)</h1>
    <br />
    <div ng-app="myApp" ng-controller="myCtrl">

        <button class="btn btn-primary" ng-click="myFunc()">Check out breeds that our service supports</button>

        <div ng-show="showMe">
            <h1>Breeds :</h1>
            <h4>pies</h4>
            <h4>kot</h4>
            <h4>kon</h4>
            <h4>swinia</h4>
            <h4>papuga</h4>
            <h4>krab</h4>
            <h4>niedzwiedz</h4>
            <h4>zyrafa</h4>
            <h3 style="color:red">donkey is default type if unsupported breed selected</h3>
        </div>

    </div>
    <script>
        var app = angular.module('myApp', []);
        app.controller('myCtrl', function ($scope) {
            $scope.showMe = false;
            $scope.myFunc = function () {
                $scope.showMe = !$scope.showMe;
            }
        });
    </script>
    <table class="table table-bordered" width="100%" style="background-color:lightyellow">
        <tr>
            <th>avatar</th>
            <th>Name</th>
            <th>Breed</th>
            <th>Sex</th>
            <th>Weight</th>
            <th>Additional Description</th>
            <th></th>
        </tr>

        @foreach (var animal in Model)
        {
            string avatarUrl = $"{@StaticDetails.AvatarUrl}{animal.AnimalType}.jpg";
            <tr>
                <td width="10%"><img src="@avatarUrl" width="100%" height="70px" style="margin:auto; display:block; border-radius:5px; border:1px solid #bbb9b9" /></td>
                <td>@animal.Name</td>
                <td>@animal.AnimalType</td>
                <td>@animal.Sex</td>
                <td>@animal.Weight</td>
                <td>@animal.AdditionalDescription</td>
                @if (StaticDetails.CurrentUserId != animal.Id)
                {
                    <td><a class="btn btn-success" asp-controller="AnimalNotDonkeys" asp-action="AddAnimalToFavourites" asp-route-Id="@animal.Id" ng-click="count = count + 1">Like It</a></td>
                }
                else
                {
                    <td><button class="btn btn-danger">Its you !</button></td>
                }
            </tr>
        }
    </table>
</body>

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Views/AnimalNotDonkeys/AllAnimalsInformations.cshtml
@model IEnumerable<AnimalWikiInformation>
@using NotDonkeyApp_UG.Data;
@{
    ViewData["Title"] = "Informations";
}
<body style="background-color:lightblue">
    <h2>Animal Wiki</h2>
    <br />
    <div ng-app="MyApp" ng-controller="MyController">
        <a class="btn btn-success" asp-controller="AnimalNotDonkeys" asp-action="AddNewAnimal">Add new Animal Info</a>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#Animal</th>
                    <th scope="col">#Informations about animal</th>
                    <th scope="col">#Help us improve</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var info in Model)
                {
                    var animalUrl = StaticDetails.AvatarUrl + info.AnimalName + ".jpg";
                    <tr>
                        <th scope="row"><img src="@animalUrl" width="30%" height="70px" style="margin:auto; display:block; border-radius:5px; border:1px solid #bbb9b9" /><br />@info.AnimalName</th>
                        <td>@info.Information</td>
                        <td>
                            <input type="button" class="btn btn-danger" value="Report Info Outdated" ng-click="ShowAlert()" />
                            <a class="btn btn-primary" asp-controller="AnimalNotDonkeys" asp-action="UpdateAnimal" asp-route-Id="@info.Id">Update Info</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.9/angular.min.js"></script>
    <script type="text/javascript">
        var app = angular.module('MyApp', [])
        app.controller('MyController', function ($scope, $window) {
            $scope.ShowAlert = function () {
                $window.alert("Hello, thank you for reporting. We will update information as soon as possible");
            }
        });
    </script>
    </body>

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Views/AnimalNotDonkeys/Create.cshtml
@model NotDonkeyApp_UG.Models.AnimalNotDonkey

@{
    ViewData["Title"] = "Create";
}

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
</head>
<body style="background-color:lightblue">
    <br />
    <h1>Create your animal profile and find its love ☜(˚▽˚)☞</h1>

    <br />
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="OwnerPhoneNumber" class="control-label">Owner Phone Number</label>
                    <input asp-for="OwnerPhoneNumber" class="form-control" />
                    <span asp-validation-for="OwnerPhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AnimalType" class="control-label">Animal Type</label>
                    <input asp-for="AnimalType" class="form-control" />
                    <span asp-validation-for="AnimalType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Sex" class="control-label"></label> [ male / female]
                    <input asp-for="Sex" class="form-control" />
                    <span asp-validation-for="Sex" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Weight" class="control-label"></label> [ kg ]
                    <input asp-for="Weight" class="form-control" />
                    <span asp-validation-for="Weight" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdditionalDescription" class="control-label">Additional Description</label>
                    <input asp-for="AdditionalDescription" class="form-control" />
                    <span asp-validation-for="AdditionalDescription" class="text-danger"></span>
                </div>
                <div ng-app="" ng-init="mySwitch=true">
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input ng-model="mySwitch" asp-for="IsDonkey" /> @Html.DisplayNameFor(model => model.IsDonkey)
                            </label>
                        </div>
                    </div>
                    <div class="form-group hidden">
                        <label asp-for="AnimalsYouLike" class="control-label"></label>
                        <input asp-for="AnimalsYouLike" class="form-control" />
                        <span asp-validation-for="AnimalsYouLike" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input ng-disabled="mySwitch" type="submit" value="Create" class="btn btn-danger" />
                    </div>
                </div>
            </form>
        </div>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Views/AnimalNotDonkeys/Index.cshtml
@model IEnumerable<AnimalNotDonkey>
@using NotDonkeyApp_UG.Data;
@{
    ViewData["Title"] = "Index";
}

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
</head>
<body style="background-color:lightblue">
    <h1 style="color:black">Welcome to our animal tinder (づ｡ ◕‿‿◕｡) づ</h1>

    <h2 style="color:dodgerblue">Join us ! </h2> <a class="btn btn-primary" asp-action="Create" asp-controller="AnimalNotDonkeys">Join us</a>
    <br />
    <h2 style="color:dodgerblue">Login ! </h2> <a class="btn btn-primary" asp-action="Login" asp-controller="AnimalNotDonkeys">Login</a>
    <br /><br />

    <br /><br />
    <div ng-app="myApp2" ng-controller="myCtrl2">

        <button class="btn btn-success" ng-click="myFunc()">Check our currently registered users</button>

        <div ng-show="showMe">
            <h1 style="color:black">List of our current animals : </h1>
            <br />
            <table class="table table-bordered" width="100%" style="background-color:lightyellow">
                <tr>
                    <th>avatar</th>
                    <th>Name</th>
                    <th>Breed</th>
                    <th>Sex</th>
                    <th>Weight</th>
                    <th>Additional Description</th>
                </tr>

                @foreach (var animal in Model)
                {
                    string avatarUrl = $"{@StaticDetails.AvatarUrl}{animal.AnimalType}.jpg";
                    <tr>
                        <td width="10%"><img src="@avatarUrl" width="100%" height="70px" style="margin:auto; display:block; border-radius:5px; border:1px solid #bbb9b9" /></td>
                        <td>@animal.Name</td>
                        <td>@animal.AnimalType</td>
                        <td>@animal.Sex</td>
                        <td>@animal.Weight</td>
                        <td>@animal.AdditionalDescription</td>
                    </tr>
                }
            </table>
        </div>

    </div>
    <script>
        var app = angular.module('myApp2', []);
        app.controller('myCtrl2', function ($scope) {
            $scope.showMe = false;
            $scope.myFunc = function () {
                $scope.showMe = !$scope.showMe;
            }
        });
    </script>

</body>

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Views/AnimalNotDonkeys/ThrowErrorMessage.cshtml
@using NotDonkeyApp_UG.Data;
@{
    ViewData["Title"] = "ThrowErrorMessage";
}

<h1 style="color:red">Ooooops ! : (  @StaticDetails.AdditionalErrorInfo</h1>
<h4 style="color:darkorange">@StaticDetails.CurrentErrorMsg</h4>
<a class="btn btn-primary" asp-controller="AnimalNotDonkeys" asp-action="Index">Go back to main page !</a>
<br />
<div>
    <td><img src="@StaticDetails.FullPathToErrorImg" width="50%" height="600px" style="margin:auto; display:block; border-radius:5px; border:1px solid #bbb9b9" /></td>
</div>
<br />

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Views/AnimalNotDonkeys/UserProfile.cshtml
@model AnimalNotDonkey
@using NotDonkeyApp_UG.Data;
@{
    ViewData["Title"] = "UserProfile";
}
<head>
    <script src="Scripts/jquery-3.0.0.js"></script>
    <script src="Scripts/popper.js"></script>
    <script src="Scripts/bootstrap.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
</head>
<body style="background-color:lightblue">
    @if (StaticDetails.CurrentUserId != -1)
    {
        <h1>✌.ʕʘ‿ʘʔ.✌</h1>
        <br />

        <h3>Phone Number : @Html.DisplayFor(x => x.OwnerPhoneNumber)</h3>
        <br />
        <style>
            #xyz {
                transition: all linear 0.5s;
                background-color: lightblue;
                height: 100px;
            }

            .ng-hide {
                height: 0;
            }
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular-animate.js"></script>

        <div ng-app="myApp">

            Hide my details : <input type="checkbox" ng-model="myCheck">

            <div ng-hide="myCheck" id="xyz">
                <h3>Breed : @Html.DisplayFor(x => x.AnimalType)</h3>
                <h3>Sex : @Html.DisplayFor(x => x.Sex)</h3>
                <h3>Weight : @Html.DisplayFor(x => x.Weight)</h3>
                <h3>Password : @Html.DisplayFor(x => x.Password)</h3>
                <h3>Name : @Html.DisplayFor(x => x.Name)</h3>
            </div>

            <script>
                var app = angular.module('myApp', ['ngAnimate']);
            </script>

        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <input type="number" id="nrtel" />
        <br /><br />
        <button class="btn btn-danger" onclick="editNumber()">Edit number</button>
        <br /><br /><br />

        <a class="btn btn-danger" onclick="hideAndDelete()" id="deleteBtn">Delete Account</a>
    }

    <a class="btn btn-primary" asp-controller="AnimalNotDonkeys" asp-action="Index">Back to main page</a>


    <br /><br />

    <script>
        function hideAndDelete() {
            deleteAccount();
            window.location.href = 'https://localhost:44357/AnimalNotDonkeys/';
        }

        function deleteAccount() {
            $.ajax({
                url: 'https://localhost:44357/RestAnimal/',
                type: 'DELETE',
                success: function (result) {
                }
            });
        }

        function editNumber() {
            var newNumber = document.getElementById("nrtel").value;

            $.ajax({
                url: 'https://localhost:44357/RestAnimal/' + newNumber,
                type: 'PUT',
                success: function (result) {
                }
            });

            window.location.href = 'https://localhost:44357/AnimalNotDonkeys/';
        }
    </script>
</body>

MVC/NotDonkeysApp/NotDonkeyMVCCoreApp/NotDonkeyApp_UG/NotDonkeyApp_UG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NotDonkeyApp_UG</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="AnimalNotDonkeys" asp-action="Index" class="navbar-brand">Animal Tinder</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="AnimalNotDonkeys" asp-action="Login">Login</a></li>
                    <li><a asp-area="" asp-controller="AnimalNotDonkeys" asp-action="PairedAnimals">Paired Animals</a></li>
                    <li><a asp-area="" asp-controller="AnimalNotDonkeys" asp-action="AllAnimals">All Animals</a></li>
                    <li><a asp-area="" asp-controller="AnimalNotDonkeys" asp-action="UserProfile">My Profile</a></li>
                    <li><a asp-area="" asp-controller="AnimalNotDonkeys" asp-action="AllAnimalsInformations">Animal Wiki</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Tinder NotForDonkey</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>